# .github/release.yml
changelog:
  categories:
    - title: ✨ New Features
      labels:
        - enhancement
    - title: 🐛 Bug Fixes
      labels:
        - bug
    - title: 📚 Documentation
      labels:
        - documentation
    - title: ⬆️ Updatebot
      labels:
        - updatebot
    - title: 🔧 Dependencies
      labels:
        - dependencies
    - title: 💥 Breaking Changes
      labels:
        - breaking-change
    - title: 🔨 Other Changes
      labels:
        - "*"
