repos:
  - repo: https://github.com/norwoodj/helm-docs
    rev: v1.3.0
    hooks:
      - id: helm-docs
  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.10
    hooks:
      - id: helmlint
