repos:
  - repo: https://github.com/norwoodj/helm-docs
    rev: v1.4.0
    hooks:
      - id: helm-docs
  - repo: https://github.com/Alfresco/alfresco-process-tools
    rev: a1162ed1f2123921b76f6a62c14fadf89fcc70d2
    hooks:
      - id: travis-yml-lint
      - id: helm-deps
      - id: helm-lint
      - id: kubepug-minimum
      - id: kubepug-recommended
      - id: checkov-helm
