repos:
  - repo: https://github.com/norwoodj/helm-docs
    rev: v1.7.0
    hooks:
      - id: helm-docs
  - repo: https://github.com/Alfresco/alfresco-build-tools
    rev: v1.2.0
    hooks:
      - id: travis-yml-lint
      - id: helm-deps
      - id: helm-lint
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
