global:
  datadog:
    enabled: true
alfresco-deployment-service:
  applications:
    datadog:
      enabled: true
      traceAgentUrl: unix:///var/run/datadog/apm.socket
      metricsExportEnabled: true
      apiKey: 25773059-6dbd-4a87-8534-be8761a78017
