global:
  gateway:
    host: "localhost"
    http: true
  keycloak:
    host: "kubernetes.docker.internal"

nginx-ingress:
  enabled: true

alfresco-content-services:
  repository:
    livenessProbe:
      initialDelaySeconds: 420
    readinessProbe:
      initialDelaySeconds: 500
    resources:
      requests:
        memory: "1800Mi"
  share:
    replicaCount: 0
    livenessProbe:
      initialDelaySeconds: 420
    readinessProbe:
      initialDelaySeconds: 500
    resources:
      requests:
        memory: "1800Mi"
  pdfrenderer:
    replicaCount: 0
  libreoffice:
    replicaCount: 0
  imagemagick:
    replicaCount: 0
  transformrouter:
    replicaCount: 0
  tika:
    replicaCount: 0
  filestore:
    replicaCount: 0

