global:
  gateway:
    host: kubernetes.docker.internal
    http: true
  keycloak:
    host: kubernetes.docker.internal

persistence:
  enabled: true
  accessModes:
    - ReadWriteOnce
  baseSize: 2Gi

alfresco-content-services:
  repository:
    replicaCount: 1
    livenessProbe:
      initialDelaySeconds: 420
    readinessProbe:
      initialDelaySeconds: 500
    resources:
      requests:
        memory: 256Mi
        limit: 512Mi
  share:
    replicaCount: 1
    livenessProbe:
      initialDelaySeconds: 420
    readinessProbe:
      initialDelaySeconds: 500
    resources:
      requests:
        memory: 256Mi
        limit: 512Mi
  pdfrenderer:
    replicaCount: 1
    resources:
      requests:
        memory: 256Mi
        limit: 512Mi
  libreoffice:
    replicaCount: 1
    resources:
      requests:
        memory: 256Mi
        limit: 512Mi
  imagemagick:
    replicaCount: 1
    resources:
      requests:
        memory: 256Mi
        limit: 512Mi
  transformrouter:
    replicaCount: 1
    resources:
      requests:
        memory: 256Mi
        limit: 512Mi
  tika:
    replicaCount: 1
    resources:
      requests:
        memory: 256Mi
        limit: 512Mi
  filestore:
    replicaCount: 1
    resources:
      requests:
        memory: 256Mi
        limit: 512Mi
