alfresco-deployment-service:
  applications:
    datadog:
      metrics:
        enabled: true
        uri: https://api.datadoghq.com
        hostTag: instance
        step: PT1M
        connectTimeout: PT1S
        readTimeout: PT10S
        batchSize: 10000
        apiKey: 25773059-6dbd-4a87-8534-be8761a78017
        applicationKey: fgdfgdfgdg
