dependencies:
  - name: common
    repository: https://activiti.github.io/activiti-cloud-helm-charts
    version: 7.1.0-M11
  - name: alfresco-identity-service
    version: 2.1.0
    repository: https://kubernetes-charts.alfresco.com/stable
    condition: alfresco-identity-service.enabled
  - name: alfresco-process-springboot-service
    alias: alfresco-modeling-service
    version: 7.1.0-M11
    repository: https://kubernetes-charts.alfresco.com/incubator
    condition: alfresco-modeling-service.enabled
  - name: postgresql
    version: 8.9.6
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: rabbitmq
    version: 7.8.0
    repository: https://charts.bitnami.com/bitnami
    condition: rabbitmq.enabled
  - name: alfresco-adf-app
    alias: alfresco-modeling-app
    version: 7.1.0-M11
    repository: https://kubernetes-charts.alfresco.com/incubator
    condition: alfresco-modeling-app.enabled
  - name: alfresco-process-springboot-service
    alias: alfresco-deployment-service
    version: 7.1.0-M11
    repository: https://kubernetes-charts.alfresco.com/incubator
    condition: alfresco-deployment-service.enabled
  - name: alfresco-adf-app
    alias: alfresco-admin-app
    version: 7.1.0-M11
    repository: https://kubernetes-charts.alfresco.com/incubator
    condition: alfresco-admin-app.enabled
