dependencies:
  - name: common
    repository: https://activiti.github.io/activiti-cloud-helm-charts
    version: 1.1.40
  - name: alfresco-identity-service
    version: 2.0.2
    repository: https://kubernetes-charts.alfresco.com/incubator
    condition: alfresco-identity-service.enabled
    alias: alfresco-identity-service
  - name: alfresco-process-springboot-service
    alias: alfresco-modeling-service
    version: 2.2.1
    repository: https://kubernetes-charts.alfresco.com/incubator
  - name: postgresql
    alias: postgresql-ams
    version: 6.3.9
    repository: https://kubernetes-charts.storage.googleapis.com
    condition: alfresco-modeling-service.postgres.enabled
  - name: alfresco-adf-app
    alias: alfresco-modeling-app
    version: 2.2.1
    repository: https://kubernetes-charts.alfresco.com/incubator
  - name: postgresql
    alias: postgresql-ads
    version: 6.3.9
    repository: https://kubernetes-charts.storage.googleapis.com
    condition: alfresco-deployment-service.enabled,alfresco-deployment-service.postgres.enabled
  - name: alfresco-process-springboot-service
    alias: alfresco-deployment-service
    version: 2.2.1
    repository: https://kubernetes-charts.alfresco.com/incubator
    condition: alfresco-deployment-service.enabled
  - name: alfresco-adf-app
    alias: alfresco-admin-app
    version: 2.2.1
    repository: https://kubernetes-charts.alfresco.com/incubator
    condition: alfresco-deployment-service.enabled,alfresco-admin-app.enabled
