dependencies:
  - name: common
    repository: https://activiti.github.io/activiti-cloud-helm-charts
    version: 1.1.21
  - name: alfresco-infrastructure
    version: 5.1.2
    repository: https://kubernetes-charts.alfresco.com/incubator
    condition: alfresco-infrastructure.enabled
  - name: nfs-server-provisioner
    version: 0.3.0
    repository: https://kubernetes-charts.storage.googleapis.com
    condition: nfs-server-provisioner.enabled
  - name: alfresco-content-services
    version: 3.0.0
    repository: https://kubernetes-charts.alfresco.com/incubator
    condition: alfresco-content-services.enabled
  - name: alfresco-process-springboot-service
    alias: alfresco-modeling-service
    version: 2.1.0
    repository: https://kubernetes-charts.alfresco.com/incubator
  - name: alfresco-process-springboot-service
    alias: alfresco-dmn-service
    version: 2.1.0
    repository: https://kubernetes-charts.alfresco.com/incubator
  - name: postgresql
    alias: postgresql-ams
    version: 0.11.0
    repository: https://kubernetes-charts.storage.googleapis.com
    condition: alfresco-modeling-service.postgres.enabled
  - name: alfresco-adf-app
    alias: alfresco-modeling-app
    version: 2.1.3
    repository: https://kubernetes-charts.alfresco.com/incubator
  - name: postgresql
    alias: postgresql-ads
    version: 0.11.0
    repository: https://kubernetes-charts.storage.googleapis.com
    condition: alfresco-deployment-service.postgres.enabled
  - name: alfresco-process-springboot-service
    alias: alfresco-deployment-service
    version: 2.1.0
    repository: https://kubernetes-charts.alfresco.com/incubator
  - name: alfresco-adf-app
    alias: alfresco-admin-app
    version: 2.1.3
    repository: https://kubernetes-charts.alfresco.com/incubator
    condition: alfresco-admin-app.enabled
  - name: alfresco-adf-app
    alias: alfresco-digital-workspace
    version: 2.1.3
    repository: https://kubernetes-charts.alfresco.com/incubator
    condition: alfresco-content-services.alfresco-digital-workspace.enabled
