dependencies:
  - name: common
    repository: https://activiti.github.io/activiti-cloud-helm-charts
    version: 1.1.28
#  - name: keycloak
#    version: 4.7.0
#    repository: https://kubernetes-charts.storage.googleapis.com
  - name: alfresco-identity-service
    version: 1.1.1
    repository: https://kubernetes-charts.alfresco.com/stable
    condition: alfresco-identity-service.enabled
    alias: alfresco-identity-service
  - name: alfresco-process-springboot-service
    alias: alfresco-modeling-service
    version: 2.1.0
    repository: https://kubernetes-charts.alfresco.com/stable
  - name: alfresco-process-springboot-service
    alias: alfresco-dmn-simulation-service
    version: 2.1.0
    repository: https://kubernetes-charts.alfresco.com/stable
  - name: postgresql
    alias: postgresql-ams
    version: 0.11.0
    repository: https://kubernetes-charts.storage.googleapis.com
    condition: alfresco-modeling-service.postgres.enabled
  - name: alfresco-adf-app
    alias: alfresco-modeling-app
    version: 2.1.4
    repository: https://kubernetes-charts.alfresco.com/incubator
  - name: postgresql
    alias: postgresql-ads
    version: 0.11.0
    repository: https://kubernetes-charts.storage.googleapis.com
    condition: alfresco-deployment-service.enabled,alfresco-deployment-service.postgres.enabled
  - name: alfresco-process-springboot-service
    alias: alfresco-deployment-service
    version: 2.1.0
    repository: https://kubernetes-charts.alfresco.com/stable
    condition: alfresco-deployment-service.enabled
  - name: alfresco-adf-app
    alias: alfresco-admin-app
    version: 2.1.4
    repository: https://kubernetes-charts.alfresco.com/incubator
    condition: alfresco-deployment-service.enabled,alfresco-admin-app.enabled
  - name: alfresco-process-springboot-service
    alias: alfresco-script-model-runtime
    version: 2.1.0
    repository: https://kubernetes-charts.alfresco.com/stable
