dependencies:
  - name: common
    repository: https://activiti.github.io/activiti-cloud-helm-charts
    version: 7.1.0-A1
  - name: alfresco-identity-service
    version: 2.1.0
    repository: https://kubernetes-charts.alfresco.com/stable
    condition: alfresco-identity-service.enabled
  - name: alfresco-process-springboot-service
    alias: alfresco-modeling-service
    version: 7.1.0-A1
    repository: https://kubernetes-charts.alfresco.com/stable
    condition: alfresco-modeling-service.enabled
  - name: postgresql
    version: 6.3.9
    repository: https://kubernetes-charts.storage.googleapis.com
    condition: postgresql.enabled
  - name: alfresco-adf-app
    alias: alfresco-modeling-app
    version: 7.1.0-A1
    repository: https://kubernetes-charts.alfresco.com/stable
    condition: alfresco-modeling-app.enabled
  - name: alfresco-process-springboot-service
    alias: alfresco-deployment-service
    version: 7.1.0-A1
    repository: https://kubernetes-charts.alfresco.com/stable
    condition: alfresco-deployment-service.enabled
  - name: alfresco-adf-app
    alias: alfresco-admin-app
    version: 7.1.0-A1
    repository: https://kubernetes-charts.alfresco.com/stable
    condition: alfresco-admin-app.enabled
