apiVersion: updatebot.jenkins-x.io/v1alpha1
kind: UpdateConfig
spec:
  rules:
    - urls:
        - https://github.com/Alfresco/alfresco-process-releases
      reusePullRequest: true
      changes:
        - regex:
            pattern: "<alfresco-process-infrastructure-deployment.version>(.*)</alfresco-process-infrastructure-deployment.version>"
            files:
              - pom.xml
