{{ if and (index .Values "setup-acs-script-job" "enabled") (index .Values "alfresco-deployment-service" "alfresco-content-services" "enabled") }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "alfresco-process-infrastructure.fullname" . }}-setup-acs-script-job
  labels:
    app: {{ template "alfresco-process-infrastructure.name" . }}
    chart: {{ template "alfresco-process-infrastructure.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    "helm.sh/hook": post-install
spec:
  template:
    spec:
      restartPolicy: "OnFailure"
      {{- if index .Values.global "registryPullSecrets" }}
      imagePullSecrets:
        {{- range $key := .Values.global.registryPullSecrets }}
        - name: {{ $key }}
        {{- end }}
      {{- end}}
      volumes:
        - name: config
          configMap:
            name: {{ template "alfresco-process-infrastructure.fullname" . }}-setup-acs-script-config
            defaultMode: 0744
      containers:
        - name: init-acs
          image: "{{ index .Values "setup-acs-script-job" "image" "repository" }}:{{ index .Values "setup-acs-script-job" "image" "tag" }}"
          command: ["/bin/bash"]
          args:
            - -c
            - /tmp/init/setup_acs.sh
          env:
            - name: "ACS_URL"
              value: "{{ template "alfresco-process-infrastructure.acs-url" . }}"
            - name: "REPOSITORY_ADMIN_USER"
              value: {{ .Values.global.acs.admin.username | quote }}
            - name: "REPOSITORY_ADMIN_PASSWORD"
              value: {{ .Values.global.acs.admin.password | quote }}
            - name: "LOAD_TEST_DATA"
              value: {{ index .Values "setup-acs-script-job" "loadTestData" | quote }}
          volumeMounts:
            - name: config
              mountPath: /tmp/init
{{ end }}
