{{ if and (index .Values "setup-acs-script-job" "enabled") (.Values.global.acs.enabled) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "alfresco-process-infrastructure.fullname" . }}-setup-acs-script-config
  labels:
    app: {{ template "alfresco-process-infrastructure.name" . }}
    chart: {{ template "alfresco-process-infrastructure.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
{{- (.Files.Glob "*.sh").AsConfig | nindent 2 }}
{{ end }}
