name: Cleanup caches for work branch
on:
  pull_request:
    types:
      - closed

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - uses: Alfresco/alfresco-build-tools/.github/actions/gh-cache-cleanup-on-merge@a28af45063d973fc5e77decb800a35c48b0838e3 # v5.29.6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
