name: Cleanup caches for work branch
on:
  pull_request:
    types:
      - closed

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - uses: Alfresco/alfresco-build-tools/.github/actions/gh-cache-cleanup-on-merge@f2259c2bb5ff4a5579d1a425cb130175a6459665 # v5.10.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
