name: Cleanup caches for work branch
on:
  pull_request:
    types:
      - closed

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - uses: Alfresco/alfresco-build-tools/.github/actions/gh-cache-cleanup-on-merge@692f336894abea26ff555cdef6e098f415c47286 # v5.28.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
