name: Cleanup caches for work branch
on:
  pull_request:
    types:
      - closed

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - uses: Alfresco/alfresco-build-tools/.github/actions/gh-cache-cleanup-on-merge@a3b8e3b43a61665b95d72425124b5ab7508bf7d5 # v5.17.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
