name: Cleanup caches for work branch
on:
  pull_request:
    types:
      - closed

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - uses: Alfresco/alfresco-build-tools/.github/actions/gh-cache-cleanup-on-merge@5d1d65a7c93fb29cd61fb0f1f279138c400a8940 # v5.27.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
