name: Cleanup caches for work branch
on:
  pull_request:
    types:
      - closed

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - uses: Alfresco/alfresco-build-tools/.github/actions/gh-cache-cleanup-on-merge@464173ee4ad8c17aa3db0808f960ecaf33dd6332 # v9.5.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
