name: Cleanup caches for work branch
on:
  pull_request:
    types:
      - closed

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - uses: Alfresco/alfresco-build-tools/.github/actions/gh-cache-cleanup-on-merge@4b0ea0ccff236b931a3cb94f4e8640525439361a # v8.12.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
