name: Cleanup caches for work branch
on:
  pull_request:
    types:
      - closed

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - uses: Alfresco/alfresco-build-tools/.github/actions/gh-cache-cleanup-on-merge@209bb4275688720e13dc0703dbd17826bf677c5c # v6.1.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
