name: Cleanup caches for work branch
on:
  pull_request:
    types:
      - closed

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - uses: Alfresco/alfresco-build-tools/.github/actions/gh-cache-cleanup-on-merge@fccbc156f8b259f2b629b391952567358d0b6329 # v5.32.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
