name: Cleanup caches for work branch
on:
  pull_request:
    types:
      - closed

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - uses: Alfresco/alfresco-build-tools/.github/actions/gh-cache-cleanup-on-merge@1889db05714b0e80ebbf17c5675bf835246dfb13 # v5.17.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
