name: Cleanup caches for work branch
on:
  pull_request:
    types:
      - closed

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - uses: Alfresco/alfresco-build-tools/.github/actions/gh-cache-cleanup-on-merge@4a622625f9863bb73651cab161bb01d30aaa1b52 # v5.16.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
