name: Cleanup caches for work branch
on:
  pull_request:
    types:
      - closed

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - uses: Alfresco/alfresco-build-tools/.github/actions/gh-cache-cleanup-on-merge@dd85d0f8fe20b558ad11af61a7105fbeffb7b47f # v5.22.6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
