name: Cleanup caches for work branch
on:
  pull_request:
    types:
      - closed

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - uses: Alfresco/alfresco-build-tools/.github/actions/gh-cache-cleanup-on-merge@0502f171476b8af38e82ce87e5fba45ecd9b17d1 # v5.28.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
