name: Cleanup caches for work branch
on:
  pull_request:
    types:
      - closed

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - uses: Alfresco/alfresco-build-tools/.github/actions/gh-cache-cleanup-on-merge@6bd620659ab8b1cac0a3b2ef3f514b1dd24086cc # v5.13.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
