name: Cleanup caches for work branch
on:
  pull_request:
    types:
      - closed

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - uses: Alfresco/alfresco-build-tools/.github/actions/gh-cache-cleanup-on-merge@38d7d54c1bceb3b4e24ca59dd78fda3f89608652 # v5.14.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
