name: Cleanup caches for work branch
on:
  pull_request:
    types:
      - closed

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - uses: Alfresco/alfresco-build-tools/.github/actions/gh-cache-cleanup-on-merge@69fdf6659761f248a9d8f546f701ff7ce1d3769d # v5.29.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
