name: Cleanup caches for work branch
on:
  pull_request:
    types:
      - closed

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - uses: Alfresco/alfresco-build-tools/.github/actions/gh-cache-cleanup-on-merge@d50e824f3a7c795b6e72ccc5a04471bc58902bf0 # v5.14.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
