name: Cleanup caches for work branch
on:
  pull_request:
    types:
      - closed

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - uses: Alfresco/alfresco-build-tools/.github/actions/gh-cache-cleanup-on-merge@4417341ffedaa187eecddf7ecf08403f3f7bb1fa # v5.24.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
