name: Cleanup caches for work branch
on:
  pull_request:
    types:
      - closed

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - uses: Alfresco/alfresco-build-tools/.github/actions/gh-cache-cleanup-on-merge@d3953ad171fd95340c9ecad9d1054561bc938cfd # v5.33.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
