name: Cleanup caches for work branch
on:
  pull_request:
    types:
      - closed

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - uses: Alfresco/alfresco-build-tools/.github/actions/gh-cache-cleanup-on-merge@3f9ef102f11edaa891eefac785b508e94f7ac0f5 # v15.9.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
