name: Cleanup caches for work branch
on:
  pull_request:
    types:
      - closed

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - uses: Alfresco/alfresco-build-tools/.github/actions/gh-cache-cleanup-on-merge@2eaedaf6e9f5c28366cbeea22c371cdce6c9c7b3 # v5.17.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
