name: Enforce PR Conventions

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - edited
    branches:
      - develop
jobs:
  enforce-pr-conventions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - name: enforce-pr-conventions
        id: git-naming-convention
        uses: Alfresco/alfresco-build-tools/.github/actions/enforce-pr-conventions@4cd0343f092e3a2b9637019f87a1fad908227c42 # v11.1.0
        with:
          jira-project-key: AAE|HXOR
