name: Enforce PR Conventions

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - edited
    branches:
      - develop
jobs:
  enforce-pr-conventions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: enforce-pr-conventions
        id: git-naming-convention
        uses: Alfresco/alfresco-build-tools/.github/actions/enforce-pr-conventions@012ce56cc25c63d5881d1ec391e2eb4c0254810d # v8.19.1
        with:
          jira-project-key: AAE|HXOR
