name: Enforce PR Conventions

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - edited
    branches:
      - develop
jobs:
  enforce-pr-conventions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: enforce-pr-conventions
        id: git-naming-convention
        uses: Alfresco/alfresco-build-tools/.github/actions/enforce-pr-conventions@ac0009fd55b474dbf50864caa4f9da36a41e5ffe # v18.21.2
        with:
          jira-project-key: AAE|HXOR|OPSEXP
