name: "Pull requests propagation check"

on:
  pull_request:
    branches:
      - develop

permissions:
  contents: read
  pull-requests: read

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name || github.run_id }}
  cancel-in-progress: true

jobs:
  PR-propagation-check:
    runs-on: ubuntu-latest
    steps:
      - name: propagation release check
        uses: Alfresco/automate-build-tools/.github/actions/github-check-pending-pr@debf558ee01bd0571c54ccef5e1208703f51af33 # v0.12.0
        if: ${{ !contains(toJson(github.event.pull_request.labels.*.name), 'fix-be-propagation') && !contains(toJson(github.event.pull_request.labels.*.name), 'be-propagation') }}
        with:
          token: ${{ secrets.BOT_GITHUB_TOKEN }}
          repo: 'alfresco-process-releases'
          days: '2'
          label: 'be-propagation'
