name: Versions propagation auto-merge
on:
  pull_request:
    types: [labeled]
    branches:
      - develop

jobs:
  versions-propagation-auto-merge:
    runs-on: ubuntu-latest
    steps:
    - uses: Alfresco/alfresco-build-tools/.github/actions/automate-propagation@5dba8511d58cb54589178d7ac339695ef52b12ef # v15.6.3
      with:
        auto-merge-token: ${{ secrets.BOT_GITHUB_TOKEN }}
        approval-token: ${{ secrets.GITHUB_TOKEN }}
