name: Versions propagation auto-merge
on:
  pull_request:
    types: [labeled]
    branches:
      - develop

jobs:
  versions-propagation-auto-merge:
    runs-on: ubuntu-latest
    steps:
    - uses: Alfresco/alfresco-build-tools/.github/actions/automate-propagation@9904c5c6fb2d8853e02ed4d9e225e5f644cda1b8 # v14.1.0
      with:
        auto-merge-token: ${{ secrets.BOT_GITHUB_TOKEN }}
        approval-token: ${{ secrets.GITHUB_TOKEN }}
